### ISSUE TITLE
Is there anyway to override the AWS endpoint to connect to local mocks of AWS services?

### ISSUE THREAD

**Issue by brunchey** [agorapulse/grails-aws-sdk#63]
Hello,

  I am looking to run an S3 server locally to support development on my laptop.  Is there a configuration value I can specify that would override the default url so I can point to my local S3 instance?

Thanks,
Ben

**Comment by musketyr** [comment]
you can change the proxy setting and then forward it to e.g. 

```
    grails:
      plugin:
        awssdk:
          s3:
              protocol: http
              proxyHost: localhost
              proxyPort: 34572
              bucket: vlad.test.agorapulse.com
```
