### ISSUE TITLE
Is it possible to override the default aws url to each service?

### ISSUE THREAD

**Issue by brunchey** [agorapulse/grails-aws-sdk#75]
Hello, 

  I would like to override the url each service should connect to so that I can develop using localstack on my Iocal machine.  Is this possible?

**Comment by musketyr** [comment]
hi,

yes it is. you can change the combination of `protocol`, `proxyPort` and `proxyHost`

```
    grails:
      plugin:
        awssdk:
          kinesis:
              protocol: http
              proxyPort: 5568
              proxyHost: localhost
```

I'll try to prepare a blog post explaining this in detail.
